### ISSUE TITLE
Weird small arrow to the right of the table

### ISSUE THREAD

**Issue by davorg** [PerlToolsTeam/psc#21]
It seems to be connected to the publication date column. Also appears on the "members" tab.

**Comment by ap** [comment]
It’s not just one arrow, it‘s three of them stacked exactly on top of each other because they’re positioned absolutely to the same spot, but there’s no `position: relative` on their respective `<th>`s in order to contain them as intended.

Except there are also `<b>` elements with arrows, which show up properly.

So the same sort arrow UI is implemented redundantly (all the way down to the JS maintaining the attributes needed for both UIs, if I’m reading it right), but where one of the copies is broken (and also uses fat arrows instead of simple ones, which IMO look less good).

**Comment by davorg** [comment]
Fixed by #26
